"""CIWT pilot product — Chapters 1–13.
Graded-style chapter checks + instructor run sheet. Original CIWT wording.
"""

def _q(text, options, correct, focus, tip):
    return {
        "q": text,
        "options": options,
        "correct": correct,
        "focus": focus,
        "keywords": [w for w in focus.lower().split() if len(w) > 3][:4],
        "study_tip": tip,
    }


PILOT_CHECKS = {
    1: [
        _q(
            "A user never had the budget share and wants it today. What kind of work is this?",
            ["Break/fix", "Service request", "Incident", "A firmware change"],
            "Service request",
            "Ticket classification",
            "1.1 — new access is a request, not a repair.",
        ),
        _q(
            "Half the building cannot badge in. First label?",
            ["Break/fix for one reader", "Service request for new badges", "Incident", "Change ticket for paint"],
            "Incident",
            "Impact and incidents",
            "1.1 — many users plus access control is an incident.",
        ),
        _q(
            "An unknown caller wants a password reset right now. What do you do first?",
            ["Reset it and sort identity later", "Verify identity per shop policy", "Disable the firewall", "Share the admin password"],
            "Verify identity per shop policy",
            "Identity",
            "1.1 / 1.4 — urgency is not identity.",
        ),
        _q(
            "Which note can the next watch actually use?",
            [
                "VPN broken",
                "Client 4.2.1, error 809, LAN ping OK, gateway ping fails, started after weekend update, hotel Wi-Fi",
                "Look into it",
                "User is difficult",
            ],
            "Client 4.2.1, error 809, LAN ping OK, gateway ping fails, started after weekend update, hotel Wi-Fi",
            "Ticket notes",
            "1.3 — action → result, not a slogan.",
        ),
        _q(
            "Correct order before a side panel comes off?",
            [
                "Open the case, then unplug",
                "Power off, unplug from the wall, wait, strap on bare skin, then open",
                "Strap over a sleeve, then pull RAM",
                "Defeat the ground pin so the outlet fits",
            ],
            "Power off, unplug from the wall, wait, strap on bare skin, then open",
            "ESD and power safety",
            "1.2 — wall unplug, not only the PSU inlet.",
        ),
        _q(
            "User felt a shock from a metal strip under the monitor. Correct move?",
            ["Swap the strip as break/fix", "Classify incident, stop, escalate", "Open the PSU to look", "Ignore it if the PC still boots"],
            "Classify incident, stop, escalate",
            "Safety as incident",
            "1.2 / 1.5 — heat and shock are not solo swaps.",
        ),
        _q(
            "Adding a production DNS record after 1500 against shop policy is:",
            ["A repair", "A change", "Optional documentation", "Always allowed if the user is loud"],
            "A change",
            "Change awareness",
            "1.3 — repairs restore a known-good state; DNS adds a change.",
        ),
        _q(
            "What belongs in the ticket?",
            ["The user’s password", "Jokes about the user", "Facts, times, tests, next step", "A rant about another shop"],
            "Facts, times, tests, next step",
            "Privacy and notes",
            "1.4 — no passwords in the ticket.",
        ),
        _q(
            "Lab ticket-intake sentence: half the quarterdeck badges failed after lunch, reader warm. Commands?",
            [
                "classify break-fix, impact 1, escalate no",
                "classify incident, impact many, escalate yes",
                "classify request, impact 1, escalate no",
                "Open the reader panel first",
            ],
            "classify incident, impact many, escalate yes",
            "Capstone intake",
            "1.5 — many users plus heat. Do not open the panel.",
        ),
        _q(
            "Closed means:",
            ["The monitor icon is green", "You left for lunch", "The required workflow works and notes are complete", "SLA minutes expired"],
            "The required workflow works and notes are complete",
            "Verification",
            "1.1 — closing is not the same as fixed.",
        ),
    ],
    2: [
        _q(
            "A 9.6 × 9.6 in board in a small office tower is which form factor?",
            ["ATX", "microATX", "Mini-ITX", "1U"],
            "microATX",
            "Form factor",
            "2.1 / hw-board card — measure the board, not the case slogan.",
        ),
        _q(
            "This course bench card socket silkscreen is LGA1700. Lab command?",
            ["socket am5", "socket lga1700", "socket 2011", "form-factor lga1700"],
            "socket lga1700",
            "CPU socket",
            "2.3 — type the silkscreen, do not press a cocked CPU.",
        ),
        _q(
            "DIMM marking on the card says DDR5. Lab command?",
            ["memory ddr4", "memory ddr5", "storage ddr5", "post ddr5"],
            "memory ddr5",
            "Memory generation",
            "2.4 — notch and generation. Do not file the notch.",
        ),
        _q(
            "M.2 stick in the short slot on the card. Storage word?",
            ["storage sata", "storage nvme", "storage hdd", "storage usb"],
            "storage nvme",
            "Storage interface",
            "2.5 — name the interface, not the brand.",
        ),
        _q(
            "Debug LED reads MEM, long beeps, no video. POST command?",
            ["post ok", "post display", "post memory", "post power"],
            "post memory",
            "POST isolation",
            "2.5 — no video after MEM is still memory, not a cable first.",
        ),
        _q(
            "Firmware (UEFI) runs:",
            ["After Windows login", "Before Windows, to check hardware and start boot", "Only on printers", "Instead of a PSU"],
            "Before Windows, to check hardware and start boot",
            "Firmware",
            "2.2 — a wrong boot order looks like a dead OS.",
        ),
        _q(
            "Secure Boot in one sentence a user will accept:",
            [
                "It makes the disk faster",
                "Firmware starts only a signed bootloader, which can also block an unsigned installer",
                "It replaces antivirus",
                "It is a kind of RAM",
            ],
            "Firmware starts only a signed bootloader, which can also block an unsigned installer",
            "Secure Boot",
            "2.2 — check Secure Boot before declaring a shop USB dead.",
        ),
        _q(
            "Why list disk before imaging?",
            ["To clean every disk automatically", "To know which handle is the OS disk", "To convert to MBR every time", "To skip About"],
            "To know which handle is the OS disk",
            "Inventory",
            "2.6 — wiping the wrong handle is the failure.",
        ),
        _q(
            "CPU cooler fan should report RPM on which header?",
            ["SYS_FAN only", "CPU_FAN (or the header firmware uses for the CPU cooler)", "USB header", "Front-panel LED"],
            "CPU_FAN (or the header firmware uses for the CPU cooler)",
            "Cooling",
            "2.3 — zero RPM in firmware is often the wrong header.",
        ),
        _q(
            "About RAM does not match the DIMM count on the board. Next?",
            ["Image the disk anyway", "Treat it as a seating or firmware problem before imaging", "Install a game launcher", "Disable Secure Boot for speed"],
            "Treat it as a seating or firmware problem before imaging",
            "Inventory vs board",
            "2.6 — About and the chassis must agree.",
        ),
    ],
    3: [
        _q(
            "M.2 is the slot. NVMe is:",
            ["Always the same thing as M.2", "A protocol that often uses that slot", "A PSU rating", "A form factor equal to ATX"],
            "A protocol that often uses that slot",
            "Storage words",
            "3.1 — a SATA M.2 stick is not NVMe.",
        ),
        _q(
            "Allowed diskpart command in this block?",
            ["clean", "list disk", "convert gpt on the OS disk without a ticket", "delete partition"],
            "list disk",
            "List disk",
            "3.1 / 2.6 — list and exit.",
        ),
        _q(
            "User deleted the share. RAID 5 saves them?",
            ["Yes, parity is a backup", "No. RAID is not backup", "Only if RAID 0", "Only if the array is degraded"],
            "No. RAID is not backup",
            "RAID vs backup",
            "3.2 — ransomware and delete are backup problems.",
        ),
        _q(
            "RAID 0 if one disk dies:",
            ["The volume stays up", "The volume is gone", "Parity rebuilds overnight", "Firmware fixes it"],
            "The volume is gone",
            "RAID 0",
            "3.2 — stripe has no fault tolerance.",
        ),
        _q(
            "May you service inside a PSU in this course?",
            ["Yes, if you see a capacitor", "No. Replace the unit", "Yes after unplugging the data cable only", "Yes if the user is important"],
            "No. Replace the unit",
            "PSU is sealed",
            "3.3 / 1.2 — sealed FRU.",
        ),
        _q(
            "No fan twitch, no LED. Cheap layer first?",
            ["Reinstall Windows", "Wall, PSU switch, 24-pin, CPU 8-pin", "Replace the CPU", "Format Disk 0"],
            "Wall, PSU switch, 24-pin, CPU 8-pin",
            "Power isolation",
            "3.3 — prove power before parts.",
        ),
        _q(
            "POST already OK, panel is dark. First idea?",
            ["Replace the motherboard", "Cable and input on the panel", "clean disk", "Disable Secure Boot"],
            "Cable and input on the panel",
            "Display path",
            "3.4 — display order starts after POST OK.",
        ),
        _q(
            "Long beeps + MEM, no video. Display cable first?",
            ["Yes", "No. That is POST memory", "Yes if HDMI", "Only on Mini-ITX"],
            "No. That is POST memory",
            "POST vs display",
            "2.5 / 3.4 — do not mix the orders.",
        ),
        _q(
            "Hot receptacle or burn smell while swapping a PSU:",
            ["Keep swapping to see if it was a fluke", "Incident, stop, escalate", "Open the PSU", "Ignore if the new unit works"],
            "Incident, stop, escalate",
            "Electrical incident",
            "3.3 — same stop rule as 1.2.",
        ),
        _q(
            "Unstable workstation capstone: you change four parts at once. Problem?",
            ["Faster", "You cannot tell what fixed it", "Required by RAID 0", "Required before list disk"],
            "You cannot tell what fixed it",
            "Isolation",
            "3.5 — one change, write the result.",
        ),
    ],
    4: [
        _q(
            "Trackpad raised, chassis hot. First move?",
            ["Keep charging it", "Pry the battery out in class", "Stop — suspected swollen pack, shop battery procedure", "Reimage Windows"],
            "Stop — suspected swollen pack, shop battery procedure",
            "Laptop battery safety",
            "4.1 — do not pry a sealed or swollen pack.",
        ),
        _q(
            "A 65 W brick on a chassis that expects 130 W often looks like:",
            ["A faster CPU", "Slow charge or throttle, not a mystery OS bug", "A dead M.2 notch", "Better thermals"],
            "Slow charge or throttle, not a mystery OS bug",
            "AC adapter",
            "4.1 — read both labels.",
        ),
        _q(
            "Mail works on cellular, fails on building Wi-Fi. Factory reset the phone?",
            ["Yes always", "No. Isolate the WLAN / portal / proxy", "Yes if MDM is installed", "Yes to remove the work profile"],
            "No. Isolate the WLAN / portal / proxy",
            "Mobile isolation",
            "4.2 — the radio works; the building path does not.",
        ),
        _q(
            "Work profile / MDM on a phone is:",
            ["The user’s personal Apple login", "Shop-managed enrollment you do not sidestep", "A kind of RAID", "Always safe to wipe in the hallway"],
            "Shop-managed enrollment you do not sidestep",
            "MDM",
            "4.2 — do not sidestep MDM to install an app.",
        ),
        _q(
            "One user cannot print from the browser; Word on the same PC works. Where do you start?",
            ["Replace the floor printer", "App / driver path for that browser", "Rebuild the print server", "Swap the PSU"],
            "App / driver path for that browser",
            "Print path",
            "4.3 — one app is not a floor outage.",
        ),
        _q(
            "Whole floor queued, panel says paper out. First test?",
            ["Rebuild a driver on the first PC in line", "Device panel / paper path", "Factory reset phones", "Disable the firewall"],
            "Device panel / paper path",
            "Print impact",
            "4.3 — many users, start at the device.",
        ),
        _q(
            "Print path order?",
            [
                "Device → cable → app",
                "App → spooler / queue → driver / port → USB or network → device panel",
                "PSU → RAID → MDM",
                "Only the driver, always",
            ],
            "App → spooler / queue → driver / port → USB or network → device panel",
            "Print path order",
            "4.3 — name the link, do not wheel a new printer first.",
        ),
        _q(
            "Ordering “a 15-inch Dell screen” without the panel code:",
            ["Good enough", "How you get the wrong FRU", "Required by UEFI", "A RAID 1 step"],
            "How you get the wrong FRU",
            "FRU identity",
            "4.1 — service tag and panel code.",
        ),
        _q(
            "gui-accounts on the bench is teaching you to:",
            ["Reset every phone", "Read who is signed in before you change an account", "Turn off MDM", "Disable Secure Boot"],
            "Read who is signed in before you change an account",
            "Account identity",
            "4.2 / 1.1 — know whose account you touch.",
        ),
        _q(
            "Portable intake pass bar?",
            [
                "You pried the pack",
                "A peer can tell from your note whether to stop for a battery, pull a driver, or work the panel",
                "You closed with no note",
                "You factory-reset a managed phone",
            ],
            "A peer can tell from your note whether to stop for a battery, pull a driver, or work the panel",
            "Capstone",
            "4.4 — same Block 1 note standard.",
        ),
    ],
    5: [
        _q(
            "What does a default gateway do for a PC?",
            ["Stores all files", "First hop off this LAN", "Assigns MAC addresses", "Replaces DNS"],
            "First hop off this LAN",
            "Gateway",
            "5.1 — address vs door vs name are different.",
        ),
        _q(
            "ipconfig shows 169.254.27.8. Meaning?",
            ["Perfect DHCP", "No usable lease (APIPA)", "DNS is fine", "The CPU is overheating"],
            "No usable lease (APIPA)",
            "APIPA",
            "5.1 — do not start a DNS lecture.",
        ),
        _q(
            "Main job of DNS for the user?",
            ["Assigns IPs", "Turns names into addresses", "Encrypts every packet", "Sets RAID"],
            "Turns names into addresses",
            "DNS",
            "5.1 / 5.3 — name path after IP path.",
        ),
        _q(
            "Ping 10.20.30.50 works. Ping app.training.local fails. Next domain?",
            ["Buy a NIC", "Name / DNS path", "Replace the PSU", "clean disk"],
            "Name / DNS path",
            "Isolation order",
            "5.3 — number works, name does not.",
        ),
        _q(
            "Flush DNS on an APIPA box?",
            ["Yes, always first", "No. Fix lease / link first", "Yes to disable the firewall", "Yes instead of ipconfig"],
            "No. Fix lease / link first",
            "Isolation misses",
            "5.3 — do not skip layers.",
        ),
        _q(
            "Port 53 in ticket language?",
            ["Web", "DNS", "RDP", "Mail submit"],
            "DNS",
            "Ports",
            "5.2 — port changes the first test.",
        ),
        _q(
            "Outlook loops but ping to the mail server IP works. NIC is dead?",
            ["Yes", "No. Path is up — name, account, or mail service next", "Yes if APIPA", "Yes on Mini-ITX only"],
            "No. Path is up — name, account, or mail service next",
            "Ping vs service",
            "5.2 — ping is not the mail door.",
        ),
        _q(
            "Hide SSID to secure the shop WLAN?",
            ["Yes, best control", "No. Fix admin password, guest isolation, and who is allowed on the LAN", "Yes instead of WPA", "Yes and disable DHCP"],
            "No. Fix admin password, guest isolation, and who is allowed on the LAN",
            "WLAN hardening",
            "5.4 — hiding the name does not hide the radio.",
        ),
        _q(
            "Changing a shared AP admin password is:",
            ["A silent repair", "A change — shop process", "Optional", "The same as ping"],
            "A change — shop process",
            "Change awareness",
            "5.4 / 1.3 — AP clicks are changes.",
        ),
        _q(
            "win-full-triage pass bar includes:",
            ["Firewall off", "Identity, IP tests, name tests, written action → result", "Reimage first", "Guess the core router"],
            "Identity, IP tests, name tests, written action → result",
            "Capstone triage",
            "5.5 — do not skip ping-IP to flushdns.",
        ),
    ],
    6: [
        _q(
            "A VM is:",
            ["Always a brand of laptop", "A guest PC made of files, running on a host", "A kind of PSU", "The same as RAID 0"],
            "A guest PC made of files, running on a host",
            "Host vs guest",
            "6.1 — this bench Windows may already be the guest.",
        ),
        _q(
            "Five guests on one host all lose the network. First thought?",
            ["Replace five NICs", "Host or shared virtual switch / uplink", "clean Disk 0 on each guest", "Disable Secure Boot"],
            "Host or shared virtual switch / uplink",
            "Shared host fault",
            "6.1 — do not treat five identical outages as five local NICs.",
        ),
        _q(
            "SaaS means you usually touch:",
            ["The vendor’s metal", "Account, license, and client", "The platform OS", "The hypervisor cluster"],
            "Account, license, and client",
            "Cloud models",
            "6.2 — mail in a browser is SaaS.",
        ),
        _q(
            "Whole tenant cannot open mail; ipconfig on the laptop is fine. Next?",
            ["Reimage the first laptop", "Vendor / tenant path, not a local disk", "format C:", "Open the PSU"],
            "Vendor / tenant path, not a local disk",
            "SaaS ticket",
            "6.2 — LAN up, tenant down.",
        ),
        _q(
            "IaaS means you still own:",
            ["Only the browser tab", "The guest OS, like Chapters 2–5", "The vendor datacenter", "Nothing"],
            "The guest OS, like Chapters 2–5",
            "IaaS",
            "6.2 — guest work is still your isolation order.",
        ),
        _q(
            "A snapshot is:",
            ["A backup in another building", "A bookmark so you can try a change and go back — not a backup", "RAID 5", "A print driver"],
            "A bookmark so you can try a change and go back — not a backup",
            "Snapshots",
            "6.3 — same punch as RAID is not backup.",
        ),
        _q(
            "Week-old snapshot chains on a host often cause:",
            ["Faster guests", "Full datastore and slow guests", "Better RAID", "Automatic backups"],
            "Full datastore and slow guests",
            "Snapshot hygiene",
            "6.3 — delete or consolidate when the change is done.",
        ),
        _q(
            "Guest shows no adapter or APIPA; host network is up. Next person?",
            ["Windows Setup", "Hypervisor owner — vNIC, port group, or host uplink", "Toner vendor", "Anyone with a screwdriver"],
            "Hypervisor owner — vNIC, port group, or host uplink",
            "Virtual NIC",
            "6.3 — isolate inside the guest first, then hand the host.",
        ),
        _q(
            "Before you blame the host for a slow VM:",
            ["Delete every snapshot", "Inventory the guest (name, RAM the guest sees)", "Reimage immediately", "Turn the firewall off"],
            "Inventory the guest (name, RAM the guest sees)",
            "Slow VM",
            "6.4 — guest facts first, host guess labeled guess.",
        ),
        _q(
            "May you delete a snapshot you do not own?",
            ["Yes if the VM is slow", "No", "Yes after lunch", "Yes if it is Tuesday"],
            "No",
            "Change ownership",
            "6.4 / 1.3 — snapshots are changes.",
        ),
    ],
    7: [
        _q(
            "Correct process order starts with:",
            ["Reimage", "Identify (who, outcome, how many, safety)", "Flush DNS", "Disable Defender"],
            "Identify (who, outcome, how many, safety)",
            "Process",
            "7.1 — do not skip identify because the user “knows it is DNS.”",
        ),
        _q(
            "User says “it’s DNS.” You skip ipconfig?",
            ["Yes", "No. Identify and a lease/IP test still come first", "Yes if they are loud", "Yes on VMs only"],
            "No. Identify and a lease/IP test still come first",
            "Do not skip layers",
            "7.1 / 5.3.",
        ),
        _q(
            "Change how many things at once?",
            ["Four, to save time", "One, then verify", "All firmware plus the disk", "Whatever the user demands"],
            "One, then verify",
            "One change",
            "7.1 — otherwise you cannot tell what worked.",
        ),
        _q(
            "Verified means:",
            ["Task Manager looks calm", "The outcome the user called about works", "SLA minutes expired", "You left a voicemail"],
            "The outcome the user called about works",
            "Verify outcome",
            "7.3 / 1.1 — closing is not the same as fixed.",
        ),
        _q(
            "MEM beep, no video. Fault domain?",
            ["SaaS", "POST / memory", "Print path", "MDM"],
            "POST / memory",
            "Fault domains",
            "7.2 / 2.5 — do not open diskpart.",
        ),
        _q(
            "Whole tenant mail down, ping 8.8.8.8 works. Domain?",
            ["Local disk", "Vendor / SaaS", "Swollen battery", "PSU internals"],
            "Vendor / SaaS",
            "SaaS domain",
            "7.2 / 6.2.",
        ),
        _q(
            "Ping IP works, ping name fails. Domain?",
            ["Power", "Name / DNS", "Display cable", "RAID 0"],
            "Name / DNS",
            "Name domain",
            "7.2 / 5.3.",
        ),
        _q(
            "Good handoff last line?",
            ["Look into it", "A person or a command", "User is difficult", "The password"],
            "A person or a command",
            "Handoff",
            "7.3 — ticket-intake note quality.",
        ),
        _q(
            "Guesses in the note should be:",
            ["Written as measured truth", "Labeled as guesses or left out", "Omitted tests", "In all caps"],
            "Labeled as guesses or left out",
            "Facts vs guesses",
            "7.3 / 1.3.",
        ),
        _q(
            "Capstone miss: diskpart on a mail-SaaS outage. Why fail?",
            ["You crossed fault domains", "You followed 7.2", "SaaS requires clean", "Always list disk"],
            "You crossed fault domains",
            "Capstone",
            "7.4 — name the domain before the lab.",
        ),
    ],
    8: [
        _q(
            "Before any install talk you must:",
            ["Type clean", "Inventory name, edition, and disks", "Disable the firewall", "Delete snapshots on a host you do not own"],
            "Inventory name, edition, and disks",
            "Inventory first",
            "8.1 / 2.6.",
        ),
        _q(
            "MEM beep, no video. Clean install?",
            ["Yes", "No. Memory domain first", "Yes if Update failed", "Yes on microATX only"],
            "No. Memory domain first",
            "Install vs POST",
            "8.1 / 2.5.",
        ),
        _q(
            "Clean install versus in-place:",
            ["Clean keeps apps; in-place wipes", "Clean wipes the OS volume; in-place tries to keep apps and files", "They are identical", "Neither is a change"],
            "Clean wipes the OS volume; in-place tries to keep apps and files",
            "Clean vs in-place",
            "8.1 — both are changes.",
        ),
        _q(
            "Why read Windows Update on a reboot loop?",
            ["Updates never cause reboots", "A pending or failed feature update is a change window, not a dead board", "To disable Defender", "To skip About"],
            "A pending or failed feature update is a change window, not a dead board",
            "Update baseline",
            "8.2.",
        ),
        _q(
            "gui-accounts is for:",
            ["Resetting every phone", "Reading who is signed in before you change an account", "Turning off MDM", "Opening a PSU"],
            "Reading who is signed in before you change an account",
            "Accounts",
            "8.2 / 4.2.",
        ),
        _q(
            "DHCP Client service stopped. Symptom?",
            ["Faster DNS", "Lease / address looks cursed", "Better RAID", "Secure Boot off"],
            "Lease / address looks cursed",
            "Services",
            "8.3 — confirm Dhcp, Dnscache, Defender Running.",
        ),
        _q(
            "Before you reboot “to clear it”:",
            ["Nothing", "List processes so you know what was running", "clean disk", "Turn the firewall off"],
            "List processes so you know what was running",
            "Processes",
            "8.3 — reboot is a change.",
        ),
        _q(
            "May you turn the firewall profile off for a game launcher?",
            ["Yes", "No", "Yes on IaaS only", "Yes after a snapshot"],
            "No",
            "Firewall",
            "8.3 / 5.2 / 1.4.",
        ),
        _q(
            "Failed Update capstone: OS still logs in. First move?",
            ["Image Disk 0", "Collect About, Update state, service states, write a note", "Open the PSU", "Factory-reset phones"],
            "Collect About, Update state, service states, write a note",
            "Failed update",
            "8.4 — no clean in class.",
        ),
        _q(
            "Chapter 8 pass bar includes:",
            ["You imaged without list disk", "You did not image, did not disable Defender, peer knows the next window", "Firewall off", "Snapshot deleted on a foreign host"],
            "You did not image, did not disable Defender, peer knows the next window",
            "Capstone",
            "8.4.",
        ),
    ],
    9: [
        _q("First habit on a strange Linux box?", ["mkfs", "Who you are, where you are, address", "Disable Defender", "clean disk"], "Who you are, where you are, address", "Linux inventory", "9.1 — same as 2.6."),
        _q("sudo is:", ["A personality", "A change with a ticket", "Always required", "A RAID level"], "A change with a ticket", "sudo", "9.1."),
        _q("Linux cousin of ipconfig /all?", ["ls", "ip a", "notepad", "diskpart clean"], "ip a", "Linux address", "9.1."),
        _q("Managed Mac mail failure. Hallway wipe?", ["Yes", "No. Isolate radio vs tenant vs MDM", "Yes if swollen", "Yes to skip FileVault"], "No. Isolate radio vs tenant vs MDM", "macOS MDM", "9.2 / 4.2."),
        _q("Swollen Mac pack?", ["Keep charging", "Stop — same as 4.1", "Pry it in class", "Reimage"], "Stop — same as 4.1", "Battery", "9.2."),
        _q("Never had the share on this Mac.", ["Break/fix NIC", "Service request / entitlement", "Incident ransomware", "clean install"], "Service request / entitlement", "Access", "9.3 / 1.1."),
        _q("Password in the cross-platform ticket?", ["Yes to help", "No", "Yes if Linux", "Yes if Mac"], "No", "Privacy", "9.3 / 1.4."),
        _q("About This Mac is the cousin of:", ["gui-about", "RAID 0", "port 3389", "APIPA"], "gui-about", "Identity", "9.2."),
        _q("Windows next door opens the share; the Mac never had it.", ["Replace the Mac NIC", "Request / entitlement, not a cable first", "format the Mac", "Disable firewall"], "Request / entitlement, not a cable first", "Mixed env", "9.4."),
        _q("Chapter 9 pass bar?", ["Hallway wipe", "Note names OS, signed-in user, request vs break/fix", "Root password in ticket", "mkfs first"], "Note names OS, signed-in user, request vs break/fix", "Capstone", "9.4."),
    ],
    10: [
        _q("Firewall profile in this course?", ["Turn it off for games", "Read it — do not turn it off", "Only on Macs", "Only after malware"], "Read it — do not turn it off", "Firewall", "10.1 / 8.3."),
        _q("Shared admin password on a monitor?", ["Fine", "Unaccountable privilege — no", "Required by SaaS", "A snapshot"], "Unaccountable privilege — no", "Privilege", "10.1."),
        _q("Mail sent as me. Label?", ["Service request", "Incident", "Repair RAM", "Print jam"], "Incident", "Malware/account", "10.2 / 1.1."),
        _q("Disable Defender so a cleaner can run?", ["Yes", "No", "Yes on IaaS", "Yes after snapshot"], "No", "Defender", "10.2."),
        _q("Malware response first job for support?", ["Become IR alone", "Contain per shop process, write facts, escalate", "Post the password", "clean disk immediately"], "Contain per shop process, write facts, escalate", "Contain", "10.2."),
        _q("Password goes:", ["In the ticket", "Not in the ticket or on the projector", "On the monitor", "In chat forever"], "Not in the ticket or on the projector", "Hygiene", "10.3."),
        _q("Patch state is:", ["Optional trivia", "Part of hygiene — read Update", "A reason to disable Defender", "A PSU rating"], "Part of hygiene — read Update", "Update", "10.3 / 8.2."),
        _q("Phish not opened. First?", ["Shame the user", "Record it; confirm no credentials entered", "Reimage", "Turn firewall off"], "Record it; confirm no credentials entered", "Phish A", "10.4."),
        _q("User typed a password on a phish.", ["Lecture only", "Incident + approved reset path", "Ignore", "Share the admin password"], "Incident + approved reset path", "Phish B", "10.4."),
        _q("Chapter 10 pass bar?", ["Password in ticket", "Factual note, no password in ticket, Defender on", "Cleaner ran", "Firewall off"], "Factual note, no password in ticket, Defender on", "Capstone", "10.4."),
    ],
    11: [
        _q("Outlook only fails; Word and the next desk work.", ["Clean image", "One app on one PC", "Floor incident", "PSU swap"], "One app on one PC", "Scope", "11.1."),
        _q("Exact error text belongs:", ["In your memory only", "In the ticket", "In a joke", "Nowhere"], "In the ticket", "Evidence", "11.1."),
        _q("App fails; ping IP works; ping name fails.", ["Office repair", "DNS domain", "Dead disk", "Swollen battery"], "DNS domain", "Isolation", "11.2 / 5.3."),
        _q("Claim the NIC is dead. First?", ["Buy a NIC", "Chapter 5 / full triage if the symptom is network", "clean", "Disable Defender"], "Chapter 5 / full triage if the symptom is network", "Controls", "11.2."),
        _q("Repair vs rebuild: default?", ["Rebuild first", "Repair / in-place before clean image", "Always clean", "Always RAID 0"], "Repair / in-place before clean image", "Repair", "11.3 / 8.1."),
        _q("Rebuild requires:", ["Hope", "Backup and a change ticket; list disk first", "Firewall off", "A game launcher"], "Backup and a change ticket; list disk first", "Rebuild", "11.3."),
        _q("Clean image because one app crashes?", ["Yes", "No. Isolate the app first", "Yes on Macs", "Yes if SaaS"], "No. Isolate the app first", "Scope miss", "11.3."),
        _q("Slow logon: reboot-loop first?", ["Yes always", "No. Inventory, Update, services, processes first", "Yes then clean", "Yes then RAID"], "No. Inventory, Update, services, processes first", "Slow logon", "11.4."),
        _q("Reboot is:", ["Free", "A change", "A backup", "A snapshot off-site"], "A change", "Change", "11.4 / 8.3."),
        _q("Chapter 11 pass bar?", ["You imaged", "One theory, one next test, no image", "diskpart on SaaS", "Password in ticket"], "One theory, one next test, no image", "Capstone", "11.4."),
    ],
    12: [
        _q("Adding production DNS after 1500 against policy is:", ["Repair", "A change", "Optional", "Always allowed"], "A change", "Change", "12.1 / 1.3."),
        _q("Reseat RAM is:", ["A change to DNS", "A repair — still document it", "A snapshot", "SaaS"], "A repair — still document it", "Repair", "12.1."),
        _q("Password in the ticket to help the next guy?", ["Yes", "No", "Yes if encrypted in your head", "Yes on Linux"], "No", "Privacy", "12.2."),
        _q("Refuse unsafe access?", ["By yelling", "Without becoming the enemy — offer the approved path", "By disabling firewall", "By sharing admin"], "Without becoming the enemy — offer the approved path", "Policy", "12.2 / 1.4."),
        _q("RAID vs backup vs snapshot?", ["All the same", "Different — RAID/snapshot are not an off-site copy", "RAID is off-site", "Snapshot is a tenant backup"], "Different — RAID/snapshot are not an off-site copy", "Recovery", "12.3 / 3.2 / 6.3."),
        _q("Ransomware on the share. RAID 5 saves them?", ["Yes", "No. Restore from backup", "Yes if RAID 0", "Yes if snapshot on the same box"], "No. Restore from backup", "Ransomware", "12.3."),
        _q("Ask last-backup time:", ["After you wipe", "Before a destructive step", "Never", "Only for printers"], "Before a destructive step", "Backup ask", "12.3."),
        _q("MEM beep ticket uses which lab family?", ["SaaS reimage", "hw-board / memory domain", "print path", "MDM wipe"], "hw-board / memory domain", "Integrated A", "12.4 / 2.5."),
        _q("Tenant mail down, good ipconfig.", ["Reimage laptop", "SaaS / vendor — not local disk", "clean", "Open PSU"], "SaaS / vendor — not local disk", "Integrated B", "12.4 / 6.2."),
        _q("Chapter 12 pass bar?", ["Domains mixed in one note with no label", "Peer can tell the domain; safety stops held", "Password listed", "Firewall off"], "Peer can tell the domain; safety stops held", "Capstone", "12.4."),
    ],
    13: [
        _q("Chapter 13 is:", ["New theory", "Lab reps for skills already taught", "A PSU course", "Official CompTIA"], "Lab reps for skills already taught", "Purpose", "13 overview."),
        _q("Before changing the lab VM:", ["clean", "Inventory", "Disable Defender", "Delete host snapshots"], "Inventory", "Setup", "13.1 / 2.6."),
        _q("ipconfig /all belongs in:", ["A novel", "The ticket as evidence", "The password field", "Nowhere"], "The ticket as evidence", "Evidence", "13.2 / 5.1."),
        _q("Release/renew is:", ["A reboot substitute for thinking", "A lease cycle when that is the domain", "A clean install", "A RAID rebuild"], "A lease cycle when that is the domain", "Lease", "13.3."),
        _q("Broken name resolution capstone labs?", ["hw-board only", "win-dns-break and win-full-triage", "diskpart clean", "gui-accounts only"], "win-dns-break and win-full-triage", "DNS labs", "13.4 / 5.5."),
        _q("Firewall during 13.4?", ["Off", "Stays on", "Optional", "Only on Macs"], "Stays on", "Firewall", "13.4."),
        _q("Settings paths gym includes:", ["About, Ethernet, Update, Accounts, Services", "PSU internals", "Hyper-V delete-all", "Printer firmware flash"], "About, Ethernet, Update, Accounts, Services", "GUI gym", "13.5."),
        _q("List processes:", ["After you reboot", "Before you reboot", "Never", "Only on Linux"], "Before you reboot", "Processes", "13.6 / 8.3."),
        _q("netsh is:", ["A different PC", "Another view of the same lease facts", "A snapshot", "A badge reader"], "Another view of the same lease facts", "netsh", "13.6."),
        _q("Chapter 13 pass bar?", ["Labs submit and notes still look like Block 1", "You typed clean", "Firewall off", "Password in ticket"], "Labs submit and notes still look like Block 1", "Capstone", "13.6."),
    ],
}


def quiz_payload(order, title):
    items = []
    for item in PILOT_CHECKS.get(order) or []:
        items.append({
            "text": item["q"],
            "options": item["options"],
            "correct": item["correct"],
            "lo": f"LO-CH-{order}",
            "lo_text": item.get("focus") or f"Chapter {order}",
            "focus": item.get("focus") or f"Chapter {order}",
            "keywords": item.get("keywords") or [],
            "study_tip": item.get("study_tip") or "",
        })
    return items


PILOT_RUN = [
    {
        "ch": 1,
        "title": "Foundations, tickets, safety",
        "minutes": 240,
        "lab": "ticket-intake",
        "pass_bar": "Submit intake: incident + many + escalate + note that does not open the hot reader.",
        "do_not": "Do not open a chassis. Do not service a PSU.",
    },
    {
        "ch": 2,
        "title": "Board, POST, inventory",
        "minutes": 280,
        "lab": "hw-board → gui-about, w11-inventory, w11-disk, gui-devices",
        "pass_bar": "hw-board submit (microATX, LGA1700, DDR5, NVMe, POST memory). Then list disk without clean.",
        "do_not": "Do not image before list disk. Do not press a cocked CPU.",
    },
    {
        "ch": 3,
        "title": "Storage, power, display",
        "minutes": 240,
        "lab": "w11-disk, hw-board review, gui-devices",
        "pass_bar": "Name RAID vs backup. PSU stays sealed. Dark panel after POST OK starts at cable/input.",
        "do_not": "Do not clean a disk. Do not open a PSU.",
    },
    {
        "ch": 4,
        "title": "Laptop FRUs, accounts, print path",
        "minutes": 180,
        "lab": "gui-accounts + paper print-path card",
        "pass_bar": "Swollen pack = stop. Print: one app vs whole floor uses different first tests.",
        "do_not": "Do not pry a sealed battery. Do not factory-reset a managed phone.",
    },
    {
        "ch": 5,
        "title": "Client network isolation",
        "minutes": 220,
        "lab": "win-ipconfig, win-dns-break, w11-wlan, win-full-triage",
        "pass_bar": "Triage lab complete. Note has action → result. Firewall stays on.",
        "do_not": "Do not flush DNS on APIPA. Do not disable the firewall.",
    },
    {
        "ch": 6,
        "title": "VMs and cloud models",
        "minutes": 160,
        "lab": "gui-about, w11-inventory; win-ipconfig inside the guest",
        "pass_bar": "Guest facts first. Snapshot ≠ backup. Whole-tenant mail is SaaS, not a reimage.",
        "do_not": "Do not delete a snapshot you do not own. Do not reimage a laptop for a tenant outage.",
    },
    {
        "ch": 7,
        "title": "Troubleshooting method",
        "minutes": 160,
        "lab": "ticket-intake + win-full-triage",
        "pass_bar": "Name the domain first. One change. Note survives 0200.",
        "do_not": "Do not diskpart a SaaS outage. Do not skip identify because the user said DNS.",
    },
    {
        "ch": 8,
        "title": "Windows client baseline",
        "minutes": 180,
        "lab": "gui-about, gui-update, gui-accounts, gui-ethernet, gui-services, w11-services, w11-processes, w11-firewall",
        "pass_bar": "Inventory before install talk. Services read as Running. Failed-update note with no clean.",
        "do_not": "Do not image. Do not disable Defender or the firewall.",
    },
    {
        "ch": 9,
        "title": "Linux, macOS, mixed access",
        "minutes": 160,
        "lab": "gui-accounts + ticket-intake (no Linux simulator)",
        "pass_bar": "Note names OS, signed-in user, request vs break/fix. No hallway wipe.",
        "do_not": "Do not mkfs. Do not pry a Mac battery. Do not put a password in the ticket.",
    },
    {
        "ch": 10,
        "title": "Endpoint security",
        "minutes": 160,
        "lab": "gui-accounts, w11-firewall, gui-services, gui-update, ticket-intake",
        "pass_bar": "Factual phish/malware note. Defender and firewall stay on. No password in the ticket.",
        "do_not": "Do not run random cleaners. Do not disable Defender.",
    },
    {
        "ch": 11,
        "title": "Software troubleshooting",
        "minutes": 160,
        "lab": "win-full-triage, gui-about, gui-update, inventory, processes, services",
        "pass_bar": "One app vs whole PC named. Repair before rebuild. No image on a single-app crash.",
        "do_not": "Do not clean. Do not skip Chapter 5 when the app is really DNS.",
    },
    {
        "ch": 12,
        "title": "Ops + integrated capstone",
        "minutes": 160,
        "lab": "ticket-intake, win-full-triage or hw-board after naming the domain",
        "pass_bar": "Change vs repair named. Peer can tell hardware vs network vs SaaS from the note.",
        "do_not": "Do not treat RAID or a snapshot as backup. Do not reimage a tenant outage.",
    },
    {
        "ch": 13,
        "title": "Windows lab gym",
        "minutes": 200,
        "lab": "Mapped CLI + GUI labs 13.1–13.6",
        "pass_bar": "Labs submit. Notes still look like Block 1.",
        "do_not": "Do not treat this chapter as new theory. Do not reboot instead of listing processes.",
    },
]


PRINT_PATH = [
    ("One user, one app", "Start at the app and driver."),
    ("One PC, every app", "Spooler, driver, port, cable. Next desk is the control."),
    ("Whole floor", "Device panel and print server. Do not rebuild the first PC’s driver."),
    ("Panel jam / paper / offline", "Device first."),
]
