"""CIWT skills midterms and finals. Original schoolhouse items. Not a vendor exam."""


def _item(text, options, correct, area):
    assert correct in options, text
    return {
        "text": text,
        "options": options,
        "correct": correct,
        "area": area,
        "focus": area,
        "lo": area,
        "lo_text": area,
        "study_tip": f"Review the {area} lessons and rerun the matching lab.",
    }


def _pack(items):
    return items


ITSUP_MIDTERM = _pack([
    _item("A user never had a share and wants it today.",
          ["Break/fix", "Service request", "Incident", "A firmware flash"],
          "Service request", "Tickets & safety"),
    _item("Half the building cannot badge. First label?",
          ["Break/fix one reader", "Service request", "Incident", "Optional note"],
          "Incident", "Tickets & safety"),
    _item("Correct order before a side panel comes off?",
          ["Open then unplug", "Power off, unplug wall, wait, strap on skin, then open", "Strap over sleeve then pull RAM", "Defeat the ground pin"],
          "Power off, unplug wall, wait, strap on skin, then open", "Tickets & safety"),
    _item("Closed means:",
          ["Green icon", "The required workflow works and notes are complete", "You left for lunch", "SLA expired"],
          "The required workflow works and notes are complete", "Tickets & safety"),
    _item("This bench card is 9.6 × 9.6 in. Form factor?",
          ["ATX", "microATX", "Mini-ITX", "1U"],
          "microATX", "Hardware"),
    _item("Debug LED MEM, long beeps, no video. Domain?",
          ["Display cable first", "POST memory", "SaaS", "Print path"],
          "POST memory", "Hardware"),
    _item("Secure Boot in one user sentence:",
          ["Makes the disk faster", "Firmware starts only a signed bootloader", "Replaces antivirus", "A kind of RAM"],
          "Firmware starts only a signed bootloader", "Hardware"),
    _item("Allowed diskpart command in this schoolhouse?",
          ["clean", "list disk", "convert gpt on OS disk with no ticket", "delete partition"],
          "list disk", "Storage & power"),
    _item("User deleted the share. RAID 5 saves them?",
          ["Yes", "No. RAID is not backup", "Only RAID 0", "Only if degraded"],
          "No. RAID is not backup", "Storage & power"),
    _item("May you service inside a PSU in this course?",
          ["Yes if you see a capacitor", "No. Replace the unit", "Yes after unplugging SATA only", "Yes if the user is important"],
          "No. Replace the unit", "Storage & power"),
    _item("POST already OK, panel dark. First idea?",
          ["Replace the board", "Cable and input on the panel", "clean disk", "Disable Secure Boot"],
          "Cable and input on the panel", "Storage & power"),
    _item("ipconfig shows 169.254.x.x. Meaning?",
          ["Perfect DHCP", "No usable lease (APIPA)", "DNS is fine", "CPU overheat"],
          "No usable lease (APIPA)", "Client network"),
    _item("Ping IP works, ping name fails. Next domain?",
          ["Buy a NIC", "Name / DNS", "Replace PSU", "clean disk"],
          "Name / DNS", "Client network"),
    _item("Flush DNS on an APIPA box?",
          ["Yes first", "No. Fix lease / link first", "Yes to kill the firewall", "Instead of ipconfig"],
          "No. Fix lease / link first", "Client network"),
    _item("A VM is:",
          ["Always a laptop brand", "A guest made of files on a host", "A PSU rating", "RAID 0"],
          "A guest made of files on a host", "Virtualization"),
    _item("A snapshot is:",
          ["An off-site backup", "A bookmark for a change — not a backup", "RAID 5", "A print driver"],
          "A bookmark for a change — not a backup", "Virtualization"),
    _item("Whole tenant mail down; laptop ipconfig is fine.",
          ["Reimage the laptop", "Vendor / SaaS path", "format C:", "Open the PSU"],
          "Vendor / SaaS path", "Virtualization"),
    _item("Password belongs:",
          ["In the ticket", "Not in the ticket", "On the monitor", "In the note subject"],
          "Not in the ticket", "Tickets & safety"),
    _item("Change one thing at a time because:",
          ["It is slower for no reason", "You cannot tell what fixed it if you change four", "RAID 0 requires it", "UEFI requires it"],
          "You cannot tell what fixed it if you change four", "Hardware"),
    _item("Default gateway is:",
          ["All files", "First hop off this LAN", "A MAC factory", "A DNS replacement"],
          "First hop off this LAN", "Client network"),
])

ITSUP_FINAL = ITSUP_MIDTERM + _pack([
    _item("Process starts with:",
          ["Reimage", "Identify who, outcome, how many, safety", "Flush DNS", "Disable Defender"],
          "Identify who, outcome, how many, safety", "Method"),
    _item("Verified means:",
          ["Task Manager is calm", "The outcome they called about works", "SLA minutes ended", "A voicemail"],
          "The outcome they called about works", "Method"),
    _item("Before any install talk:",
          ["Type clean", "Inventory name, edition, disks", "Disable firewall", "Delete foreign snapshots"],
          "Inventory name, edition, disks", "Windows client"),
    _item("DHCP Client service stopped often looks like:",
          ["Faster DNS", "A cursed lease / address", "Better RAID", "Secure Boot off"],
          "A cursed lease / address", "Windows client"),
    _item("Firewall profile in this course?",
          ["Off for games", "Read it — do not turn it off", "Macs only", "After malware only"],
          "Read it — do not turn it off", "Security"),
    _item("Disable Defender so a cleaner can run?",
          ["Yes", "No", "Yes on IaaS", "Yes after a snapshot"],
          "No", "Security"),
    _item("Phish opened and a password typed:",
          ["Lecture only", "Incident plus approved reset path", "Ignore", "Share the admin password"],
          "Incident plus approved reset path", "Security"),
    _item("Outlook only fails; Word and the next desk work.",
          ["Clean image", "One app on one PC", "Floor incident", "PSU swap"],
          "One app on one PC", "Software"),
    _item("Repair vs rebuild default?",
          ["Rebuild first", "Repair / in-place before a clean image", "Always clean", "Always RAID 0"],
          "Repair / in-place before a clean image", "Software"),
    _item("Adding production DNS after 1500 against policy is:",
          ["A repair", "A change", "Optional", "Always allowed"],
          "A change", "Operations"),
    _item("Ransomware on the share. RAID 5 saves them?",
          ["Yes", "No. Restore from backup", "Yes if RAID 0", "Yes if local snapshot only"],
          "No. Restore from backup", "Operations"),
    _item("Swollen laptop pack:",
          ["Keep charging", "Stop — shop battery procedure", "Pry it in class", "Reimage"],
          "Stop — shop battery procedure", "Hardware"),
    _item("Print: whole floor queued, panel says paper out. First test?",
          ["Rebuild the first PC driver", "Device panel / paper path", "Factory-reset phones", "Disable firewall"],
          "Device panel / paper path", "Software"),
    _item("Hide SSID to secure the shop WLAN?",
          ["Yes best control", "No. Fix admin password, guest isolation, and who is allowed", "Yes instead of WPA", "Yes and disable DHCP"],
          "No. Fix admin password, guest isolation, and who is allowed", "Client network"),
    _item("May you delete a snapshot you do not own?",
          ["Yes if the VM is slow", "No", "Yes after lunch", "Yes on Tuesdays"],
          "No", "Virtualization"),
])

CLIENT_MIDTERM = _pack([
    _item("MEM beep, no video. Clean install?",
          ["Yes", "No. Memory domain first", "Yes if Update failed", "Yes on microATX"],
          "No. Memory domain first", "Windows client"),
    _item("Why read Windows Update on a reboot loop?",
          ["Updates never reboot", "A failed feature update is a change window, not a dead board", "To disable Defender", "To skip About"],
          "A failed feature update is a change window, not a dead board", "Windows client"),
    _item("gui-accounts is for:",
          ["Resetting every phone", "Reading who is signed in before you change an account", "Turning off MDM", "Opening a PSU"],
          "Reading who is signed in before you change an account", "Windows client"),
    _item("First habit on a strange Linux box?",
          ["mkfs", "Who you are, where you are, address", "Disable Defender", "clean disk"],
          "Who you are, where you are, address", "Cross-platform"),
    _item("Managed Mac mail fail. Hallway wipe?",
          ["Yes", "No. Isolate radio vs tenant vs MDM", "Yes if swollen", "Yes to skip FileVault"],
          "No. Isolate radio vs tenant vs MDM", "Cross-platform"),
    _item("Never had the share on this Mac.",
          ["Break/fix the NIC", "Service request / entitlement", "Incident ransomware", "clean install"],
          "Service request / entitlement", "Cross-platform"),
    _item("Shared admin password on a monitor?",
          ["Fine", "Unaccountable privilege — no", "Required by SaaS", "A snapshot"],
          "Unaccountable privilege — no", "Security"),
    _item("Mail sent as me. Label?",
          ["Service request", "Incident", "Repair RAM", "Print jam"],
          "Incident", "Security"),
    _item("Password on a ticket?",
          ["Yes to help", "No", "Yes if Linux", "Yes if Mac"],
          "No", "Security"),
    _item("Patch state is:",
          ["Trivia", "Hygiene — read Update", "A reason to disable Defender", "A PSU rating"],
          "Hygiene — read Update", "Windows client"),
])

CLIENT_FINAL = CLIENT_MIDTERM + _pack([
    _item("Outlook only fails.",
          ["Clean image", "One app on one PC", "Floor outage", "Open PSU"],
          "One app on one PC", "Software"),
    _item("App fails; ping IP works; ping name fails.",
          ["Office repair", "DNS domain", "Dead disk", "Swollen battery"],
          "DNS domain", "Software"),
    _item("Rebuild requires:",
          ["Hope", "Backup, a change ticket, list disk first", "Firewall off", "A game launcher"],
          "Backup, a change ticket, list disk first", "Software"),
    _item("Slow logon: reboot-loop first?",
          ["Yes", "No. Inventory, Update, services, processes first", "Yes then clean", "Yes then RAID"],
          "No. Inventory, Update, services, processes first", "Software"),
    _item("Adding DNS after 1500 against policy:",
          ["Repair", "A change", "Optional", "Always allowed"],
          "A change", "Operations"),
    _item("RAID vs backup vs snapshot?",
          ["The same", "Different — RAID/snapshot are not an off-site copy", "RAID is off-site", "Snapshot is tenant backup"],
          "Different — RAID/snapshot are not an off-site copy", "Operations"),
    _item("List processes:",
          ["After reboot", "Before reboot", "Never", "Linux only"],
          "Before reboot", "Windows client"),
    _item("Firewall during a name-resolution lab?",
          ["Off", "Stays on", "Optional", "Macs only"],
          "Stays on", "Security"),
    _item("Tenant mail down, good ipconfig.",
          ["Reimage laptop", "SaaS / vendor — not local disk", "clean", "Open PSU"],
          "SaaS / vendor — not local disk", "Operations"),
    _item("Chapter gym pass bar?",
          ["Labs submit and notes still look like Block 1", "You typed clean", "Firewall off", "Password in ticket"],
          "Labs submit and notes still look like Block 1", "Operations"),
])

NETOPS_MIDTERM = _pack([
    _item("OSI for a beginner is:",
          ["A law that forbids TCP", "A layered way to talk about network functions", "A switch brand", "A fiber connector"],
          "A layered way to talk about network functions", "Models & addressing"),
    _item("A router primarily does what a pure L2 switch does not:",
          ["Forward between IP networks", "Learn only MAC addresses", "Assign printer drivers", "Make thermal paste"],
          "Forward between IP networks", "Routing"),
    _item("A subnet mask tells a host:",
          ["Which bits are network vs host", "The DNS password", "The printer model", "BIOS version"],
          "Which bits are network vs host", "Models & addressing"),
    _item("A switch forwards based on:",
          ["MAC learning", "Only DNS", "Only RAID", "Only toner"],
          "MAC learning", "Switching"),
    _item("Access port vs trunk in ticket language:",
          ["Access is one VLAN; trunk carries more than one", "They are identical", "Trunk is for printers only", "Access is Layer 3 only"],
          "Access is one VLAN; trunk carries more than one", "Switching"),
    _item("Default gateway for a PC is:",
          ["The file server", "First hop off this LAN", "The printer queue", "The PSU"],
          "First hop off this LAN", "Models & addressing"),
    _item("Ping is useful because:",
          ["It verifies basic IP reachability when ICMP is allowed", "It repairs the OS", "It creates users", "It measures toner"],
          "It verifies basic IP reachability when ICMP is allowed", "Operations"),
    _item("APIPA is a clue that:",
          ["DHCP worked", "The client likely failed to get a lease", "CPU is hot", "Disk is GPT"],
          "The client likely failed to get a lease", "Services"),
    _item("VLAN mis-match on an access port often looks like:",
          ["A good trunk", "The user is on the wrong L2 segment", "A faster WAN", "Better RAID"],
          "The user is on the wrong L2 segment", "Switching"),
    _item("Two interfaces up with no route between them until:",
          ["You paint the rack", "Routing / connected networks exist", "You disable ICMP", "You format a disk"],
          "Routing / connected networks exist", "Routing"),
])

NETOPS_FINAL = NETOPS_MIDTERM + _pack([
    _item("DNS for users mainly:",
          ["Assigns IPs", "Turns names into addresses", "Encrypts every packet", "Sets RAID"],
          "Turns names into addresses", "Services"),
    _item("DHCP mainly automates:",
          ["Certificates only", "IP, mask, gateway, DNS to clients", "RAID rebuilds", "UEFI updates"],
          "IP, mask, gateway, DNS to clients", "Services"),
    _item("Port 53 in ticket language?",
          ["Web", "DNS", "RDP", "Mail submit"],
          "DNS", "Services"),
    _item("NAT in a small office often means:",
          ["Private PCs share one public address toward the Internet", "Formatting disks", "Assigning SIDs", "Updating UEFI"],
          "Private PCs share one public address toward the Internet", "Services"),
    _item("Prefer WPA2/WPA3 over legacy weak Wi-Fi because:",
          ["Stronger protection on the wireless medium", "Faster spinning disks", "Automatic VLANs", "No passwords needed"],
          "Stronger protection on the wireless medium", "Hardening"),
    _item("Hide SSID as the main WLAN control?",
          ["Yes", "No. Fix admin password, guest isolation, who is allowed", "Yes instead of WPA", "Yes and disable DHCP"],
          "No. Fix admin password, guest isolation, who is allowed", "Hardening"),
    _item("Changing a shared AP admin password is:",
          ["A silent repair", "A change — shop process", "Optional", "The same as ping"],
          "A change — shop process", "Hardening"),
    _item("Name works? Prove with:",
          ["Toner density", "Ping IP then ping name / nslookup", "diskpart clean", "Disable firewall"],
          "Ping IP then ping name / nslookup", "Operations"),
    _item("Many users lose the network after a switch change. Domain?",
          ["One NIC on the first desk", "Plant / VLAN / uplink", "A single Outlook profile", "A laptop battery"],
          "Plant / VLAN / uplink", "Operations"),
    _item("Document a network change with:",
          ["Nothing", "What you typed, what show commands returned, how to undo", "Only a joke", "The user password"],
          "What you typed, what show commands returned, how to undo", "Operations"),
])


SPECS = {
    "ITSUP": [
        ("Skills Midterm — IT Support", "Chapters 1–6 skills. 20 items. Pass 80%. 40 minutes.", 10, ITSUP_MIDTERM, 40, 80),
        ("Skills Final — IT Support", "Full ITSUP skills. 35 items. Pass 80%. 60 minutes. Timer auto-submits.", 20, ITSUP_FINAL, 60, 80),
    ],
    "NETOPS": [
        ("Skills Midterm — Network Operations", "Models, switching, routing. 10 items. Pass 80%. 30 minutes.", 10, NETOPS_MIDTERM, 30, 80),
        ("Skills Final — Network Operations", "Full NETOPS skills. 20 items. Pass 80%. 45 minutes. Timer auto-submits.", 20, NETOPS_FINAL, 45, 80),
    ],
    "CLIENT": [
        ("Skills Midterm — Client Systems", "Windows, mixed OS, security. 10 items. Pass 80%. 30 minutes.", 10, CLIENT_MIDTERM, 30, 80),
        ("Skills Final — Client Systems", "Full client-ops skills. 20 items. Pass 80%. 45 minutes. Timer auto-submits.", 20, CLIENT_FINAL, 45, 80),
    ],
}


def exams_for(code):
    return SPECS.get(code) or []
